name: ClientTests

on:
  push:
  pull_request:
    branches:
      - 'develop'
      - 'master'
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: cd client && npm install && npm run test:ci
