name: ClientTests

on:
  push:
  pull_request:
    branches:
      - 'develop'
      - 'master'
      - 'release/*'
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: cd refurbify/client && npm install && npm run test:ci
